[build]
  command = "npm run build"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[[headers]]
  for = "*.jpg", "*.jpeg", "*.png"
  [headers.values]
    cache-control= "max-age=604800"