[build]
  command = "npm run build"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[[headers]]
  content-type: "ext/html; charset=utf-8"
  [headers.values]
    cache-control= "max-age=604800"